### PR TITLE
Added `stroke` prop + nullish coalescing

### PR DESCRIPTION
**Pull request by ndom91**
Added the `stroke` prop in addition to `color`, and `size` for each icon. As well as set the default values with the new nullish coalescing operator (`??`) instead of _or_ (`||`).

### CODE REVIEW

**Comment by ndom91** [comment]
@ForsakenHarmony btw what's up with the deleting of the props after copying them into local variables? Never seen that before, what's the advantage?

**Comment by ForsakenHarmony** [comment]
I think it's because the prop names are different and I spread props onto the element

**Comment by ForsakenHarmony** [comment]
Also did you forget to commit `bin/build.js`? (hope you didn't edit manually)

**Comment by ndom91** [comment]
@ForsakenHarmony ne ist da - [bin/build.js](https://github.com/ndom91/preact-feather/blob/feat-stroke/bin/build.js) habe ich nicht angefasst

**Comment by ndom91** [comment]
@ForsakenHarmony ahh I didnt even see this til now. So I see the element gets generated in there, but even after the build step it didnt get "regenerated" or anything. Why not edit it by hand?

**Comment by ndom91** [comment]
@ForsakenHarmony okay okay I finally understand what you mean haha. So I adjusted `build.js`, will commit it shortly. 

Also I did edit the icons previously "by hand" but it was just 3-4 find and replaces, not entirely by hand haha.

**Comment by ndom91** [comment]
I put the nullish coalescing change into a separate commit so you can roll it back more easily in case you don't want to support it.

According to [caniuse.com](https://caniuse.com/#search=nullish%20coalescing) theres not that much support yet and I didnt see babel in any of your build steps so feel free to do it with it what you please.

**Comment by ForsakenHarmony** [comment]
It generates the components directly from the feathers svg icons, if you previously edited them all and now set the build script to output the exact same, nothing should change

**Comment by ndom91** [comment]
Yup, all good.

**Comment by ForsakenHarmony** [comment]
Doesn't really look like you ran the build npm script after changing the file or didn't check it in, either way, microbundle doesn't really support nullish coalescing yet

**Comment by ForsakenHarmony** [comment]
Also not sure if I'm the biggest fan because `stroke` actually is an svg property you might want to pass (not that you'd need to because color aliases it, but still)

**Comment by ForsakenHarmony** [comment]
You can currently just pass `stroke-width` which will override the default

**Comment by ndom91** [comment]
Haha okay, I tried to override the `stroke-width` with inline css but it didnt work, thats why I went about this to begin with. Maybe I messed something up though

**Comment by ForsakenHarmony** [comment]
pass it as a prop, not inline css

**Pull request closed without merging**
