### PR TITLE
Remove conversion to React-style SVG attributes

### LINKED ISSUE #1: SVG attributes are broken
Hi! :wave: First off: thanks for this library!

I noticed that icon rendering was a off for me, and it was especially noticable on the info icon, which looks like this for me right now:

screenshot from 2018-03-14 20-03-11

Turns out that the library treats all SVG attributes as camelCase. This is fine for React because it [translates](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes) those attributes to kebab-case, but Preact doesn't do this.

I _could_ work around it by using `preact-compat`, but in that case I might as well also use `react-feather` instead, and I really want to try to keep it Preact-only and avoid any unnecessary dependencies.

I'm willing to open a PR to update all the attributes if you want. :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by koenkivits**
Fixes #1

The fix turned out to be just removing 2 lines from the build script.

### CODE REVIEW

**Comment by koenkivits** [comment]
Yes!

Before:
screenshot from 2018-03-15 22-01-21

After:
screenshot from 2018-03-15 22-02-06

**Comment by ForsakenHarmony** [comment]
Cool, thx

**Comment by ForsakenHarmony** [comment]
Published as 2.0.1 (forgot to build in 2.0.0 🙈)

**Comment by koenkivits** [comment]
It happens. :smile: 

Thanks!

**Pull request merged**
